on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Yarn Install
        run: |
             npm ci
             npm i -g corepack
             yarn install
      - name: Build application
        run: |
             cd ./android
             chmod 777 gradlew
             ./gradlew assembleRelease
      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./android/app/build/outputs
          retention-days: 2
